=== api-evangelist/etsy/json-schema/open-api-v3-shop-shipping-profile-destination-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ShopShippingProfileDestination",
  "description": "Represents a shipping destination assigned to a shipping profile.",
  "$id": "https://raw.githubusercontent.com/api-evangelist/etsy/refs/heads/main/json-schema/open-api-v3-shop-shipping-profile-destination-schema.json",
  "type": "object",
  "properties": {
    "shipping_profile_destination_id": {
      "type": "integer",
      "description": "The numeric ID of the shipping profile destination in the [shipping profile](/documentation/reference#tag/Shop-ShippingProfile) associated with the listing.",
      "format": "int64",
      "minimum": 1,
      "example": 1
    },
    "shipping_profile_id": {
      "type": "integer",
      "description": "The numeric ID of the shipping profile.",
      "format": "int64",
      "minimum": 1,
      "example": 1
    },
    "origin_country_iso": {
      "type": "string",
      "description": "The ISO code of the country from which the listing ships.",
      "format": "ISO 3166-1 alpha-2",
      "example": "US"
    },
    "destination_country_iso": {
      "type": "string",
      "description": "The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided.",
      "example": "US"
    },
    "destination_region": {
      "type": "string",
      "description": "The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If `none`, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided.",
      "enum": [
        "eu",
        "non_eu",
        "none"
      ],
      "example": "eu"
    },
    "primary_cost": {
      "description": "The cost of shipping to this country/region alone, measured in the store's default currency.",
      "oneOf": [
        {
          "$ref": "#/components/schemas/Money"
        }
      ],
      "example": "example"
    },
    "secondary_cost": {
      "description": "The cost of shipping to this country/region with another item, measured in the store's default currency.",
      "oneOf": [
        {
          "$ref": "#/components/schemas/Money"
        }
      ],
      "example": "example"
    },
    "shipping_carrier_id": {
      "type": "integer",
      "description": "The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.",
      "nullable": true,
      "example": 1
    },
    "mail_class": {
      "type": "string",
      "description": "The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.",
      "nullable": true,
      "example": "example string"
    },
    "min_delivery_days": {
      "type": "integer",
      "description": "The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.",
      "nullable": true,
      "minimum": 1,
      "maximum": 45,
      "example": 1
    },
    "max_delivery_days": {
      "type": "integer",
      "description": "The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.",
      "nullable": true,
      "minimum": 1,
      "maximum": 45,
      "example": 1
    }
  }
}

=== api-evangelist/etsy/examples/open-api-v3-shop-shipping-profile-destination-example.json
{
  "shipping_profile_destination_id": 1,
  "shipping_profile_id": 1,
  "origin_country_iso": "US",
  "destination_country_iso": "US",
  "destination_region": "eu",
  "primary_cost": "example",
  "secondary_cost": "example",
  "shipping_carrier_id": 1,
  "mail_class": "example string",
  "min_delivery_days": 1,
  "max_delivery_days": 1
}
