=== api-evangelist/etsy/json-schema/open-api-v3-buyer-taxonomy-node-property-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "BuyerTaxonomyNodeProperty",
  "description": "A product property definition.",
  "$id": "https://raw.githubusercontent.com/api-evangelist/etsy/refs/heads/main/json-schema/open-api-v3-buyer-taxonomy-node-property-schema.json",
  "type": "object",
  "properties": {
    "property_id": {
      "type": "integer",
      "description": "The unique numeric ID of this product property.",
      "format": "int64",
      "minimum": 1,
      "example": 1
    },
    "name": {
      "type": "string",
      "description": "The name string for this taxonomy node.",
      "example": "Handmade Ceramic Mug"
    },
    "display_name": {
      "type": "string",
      "description": "The human-readable product property name string.",
      "example": "Handmade Ceramic Mug"
    },
    "scales": {
      "type": "array",
      "description": "A list of available scales.",
      "items": {
        "description": "A list of available scales.",
        "oneOf": [
          {
            "$ref": "#/components/schemas/BuyerTaxonomyPropertyScale"
          }
        ]
      }
    },
    "is_required": {
      "type": "boolean",
      "description": "When true, listings assigned eligible taxonomy IDs require this property.",
      "example": true
    },
    "supports_attributes": {
      "type": "boolean",
      "description": "When true, you can use this property in listing properties.",
      "example": true
    },
    "supports_variations": {
      "type": "boolean",
      "description": "When true, you can use this property in listing inventory.",
      "example": true
    },
    "is_multivalued": {
      "type": "boolean",
      "description": "When true, you can assign multiple property values to this property",
      "example": true
    },
    "max_values_allowed": {
      "type": "integer",
      "description": "When true, you can assign multiple property values to this property",
      "nullable": true,
      "example": 1
    },
    "possible_values": {
      "type": "array",
      "description": "A list of supported property value strings for this property.",
      "items": {
        "description": "A list of supported property value strings for this property.",
        "oneOf": [
          {
            "$ref": "#/components/schemas/BuyerTaxonomyPropertyValue"
          }
        ]
      }
    },
    "selected_values": {
      "type": "array",
      "description": "A list of property value strings automatically and always selected for the given property.",
      "items": {
        "description": "A list of property value strings automatically and always selected for the given property.",
        "oneOf": [
          {
            "$ref": "#/components/schemas/BuyerTaxonomyPropertyValue"
          }
        ]
      }
    }
  }
}

=== api-evangelist/etsy/examples/open-api-v3-taxonomy-node-property-example.json
{
  "property_id": 1,
  "name": "Handmade Ceramic Mug",
  "display_name": "Handmade Ceramic Mug",
  "scales": [
    {},
    {}
  ],
  "is_required": true,
  "supports_attributes": true,
  "supports_variations": true,
  "is_multivalued": true,
  "max_values_allowed": 1,
  "possible_values": [
    {},
    {}
  ],
  "selected_values": [
    {},
    {}
  ]
}
